#app.yml file src/main/resources
    
runtime: java11
env: flex
  
handlers:  
    - url: /.*
    script: this field is required, but ignored
    secure: always
manual_scaling:
    instances: 1
   
resources:
    cpu: 2
    memory_gb: 2.3
    disk_size_gb: 5
