#app.yml file src/main/resources
    
runtime: java
env: flex

runtime_config:
    operating_system: "ubuntu18"
    runtime_version: "11"

manual_scaling:
    instances: 1
 
resources:
    cpu: 2
    memory_gb: 2.3
    disk_size_gb: 10
